-- =============================================================================
-- 02_create_staging.sql
-- Camada de staging e tabelas de controle do ETL.
--
--   psql -h localhost -U postgres -d dm_anp_pernambuco -f sql/02_create_staging.sql
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Controle de cargas: uma linha por arquivo processado em cada execução.
-- Um arquivo com status CONCLUIDO (mesmo nome + mesmo tamanho) é ignorado nas
-- execuções seguintes, evitando reprocessamento.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS etl_controle_carga (
    id_carga                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_arquivo              VARCHAR(255) NOT NULL,
    caminho_arquivo           TEXT,
    tamanho_bytes             BIGINT,
    data_modificacao_arquivo  TIMESTAMP,
    data_inicio               TIMESTAMP    NOT NULL DEFAULT now(),
    data_fim                  TIMESTAMP,
    quantidade_lida           INTEGER,
    quantidade_processada     INTEGER,
    quantidade_rejeitada      INTEGER,
    quantidade_fora_escopo    INTEGER,
    quantidade_outras_uf      INTEGER,      -- linhas de outros estados descartadas na leitura (01)
    status                    VARCHAR(20)  NOT NULL,
    mensagem                  TEXT,
    CONSTRAINT ck_controle_status CHECK (status IN ('PROCESSANDO', 'CONCLUIDO', 'ERRO'))
);

-- Garante que o mesmo arquivo (nome + tamanho) só fique CONCLUIDO uma vez.
CREATE UNIQUE INDEX IF NOT EXISTS ux_controle_arquivo_concluido
    ON etl_controle_carga (nome_arquivo, tamanho_bytes)
    WHERE status = 'CONCLUIDO';

-- -----------------------------------------------------------------------------
-- Staging bruta: espelho das 16 colunas do CSV bruto da ANP (série histórica
-- semestral de combustíveis automotivos), tudo em TEXT, sem nenhuma conversão.
-- Truncada no início de cada execução.
--   Regiao - Sigla -> regiao | Estado - Sigla -> estado | Municipio -> municipio
--   Revenda -> revenda | CNPJ da Revenda -> cnpj | Nome da Rua -> rua
--   Numero Rua -> numero | Complemento | Bairro | Cep | Produto
--   Data da Coleta -> data_coleta | Valor de Venda -> valor_venda
--   Valor de Compra -> valor_compra | Unidade de Medida -> unidade_medida | Bandeira
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS stg_precos_combustiveis (
    id_staging      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_arquivo    VARCHAR(255) NOT NULL,
    linha_origem    INTEGER,
    data_carga      TIMESTAMP    NOT NULL DEFAULT now(),
    -- colunas originais da ANP (mesma ordem do arquivo bruto)
    regiao          TEXT,
    estado          TEXT,
    municipio       TEXT,
    revenda         TEXT,
    cnpj            TEXT,
    rua             TEXT,
    numero          TEXT,
    complemento     TEXT,
    bairro          TEXT,
    cep             TEXT,
    produto         TEXT,
    data_coleta     TEXT,
    valor_venda     TEXT,
    valor_compra    TEXT,
    unidade_medida  TEXT,
    bandeira        TEXT
);

-- -----------------------------------------------------------------------------
-- Staging limpa: resultado da transformação 02 (dados tipados, padronizados,
-- filtrados para PE/período e sem duplicidades). Fonte das dimensões e da fato.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS stg_precos_limpos (
    id_staging      BIGINT        PRIMARY KEY,
    id_carga        BIGINT,
    nome_arquivo    VARCHAR(255)  NOT NULL,
    linha_origem    INTEGER,
    regiao          VARCHAR(5),
    uf              CHAR(2)       NOT NULL,
    estado_nome     VARCHAR(50),
    municipio       VARCHAR(100)  NOT NULL,
    revenda         VARCHAR(200),
    cnpj            VARCHAR(18)   NOT NULL,
    rua             VARCHAR(200),
    numero          VARCHAR(30),
    complemento     VARCHAR(200),
    bairro          VARCHAR(100),
    cep             VARCHAR(9),
    produto         VARCHAR(60)   NOT NULL,
    categoria       VARCHAR(60),
    unidade_medida  VARCHAR(20),
    bandeira        VARCHAR(100)  NOT NULL,
    data_coleta     DATE          NOT NULL,
    valor_venda     NUMERIC(12,2) NOT NULL,
    valor_compra    NUMERIC(12,2)
);

-- -----------------------------------------------------------------------------
-- Registros rejeitados: nada é descartado em silêncio.
-- dados_originais guarda a linha original da staging em JSON (texto).
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS etl_rejeitados (
    id_rejeicao      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_carga         BIGINT,
    nome_arquivo     VARCHAR(255),
    linha_origem     INTEGER,
    etapa            VARCHAR(30)  NOT NULL,
    motivo           VARCHAR(50)  NOT NULL,
    detalhe          TEXT,
    data_rejeicao    TIMESTAMP    NOT NULL DEFAULT now(),
    dados_originais  TEXT
);

COMMENT ON TABLE stg_precos_combustiveis IS 'Staging bruta: colunas da ANP em TEXT, sem tratamento';
COMMENT ON TABLE stg_precos_limpos       IS 'Staging limpa: dados tipados e validados, fonte do Data Mart';
COMMENT ON TABLE etl_rejeitados         IS 'Registros que não puderam ser carregados e o motivo';
COMMENT ON TABLE etl_controle_carga      IS 'Controle de arquivos carregados (evita duplicar cargas)';
