-- =============================================================================
-- 03_create_dimensions.sql
-- Dimensões do Data Mart (surrogate keys geradas pelo PostgreSQL).
--
--   psql -h localhost -U postgres -d dm_anp_pernambuco -f sql/03_create_dimensions.sql
-- =============================================================================

-- -----------------------------------------------------------------------------
-- dim_tempo: um registro por dia de 2021-01-01 a 2026-06-30.
-- id_tempo usa o formato AAAAMMDD (ex.: 20240315). É uma surrogate key
-- inteira, estável e legível, prática recomendada por Kimball para datas.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dim_tempo (
    id_tempo         INTEGER      PRIMARY KEY,
    data             DATE         NOT NULL,
    dia              SMALLINT     NOT NULL,
    mes              SMALLINT     NOT NULL,
    nome_mes         VARCHAR(10)  NOT NULL,
    trimestre        SMALLINT     NOT NULL,
    semestre         SMALLINT     NOT NULL,
    ano              SMALLINT     NOT NULL,
    periodo          VARCHAR(6)   NOT NULL,   -- ex.: 2024.1
    dia_semana       SMALLINT     NOT NULL,   -- 1 = domingo ... 7 = sábado
    nome_dia_semana  VARCHAR(15)  NOT NULL,
    CONSTRAINT uq_dim_tempo_data   UNIQUE (data),
    CONSTRAINT ck_dim_tempo_mes    CHECK (mes BETWEEN 1 AND 12),
    CONSTRAINT ck_dim_tempo_trim   CHECK (trimestre BETWEEN 1 AND 4),
    CONSTRAINT ck_dim_tempo_sem    CHECK (semestre IN (1, 2))
);

-- -----------------------------------------------------------------------------
-- dim_combustivel: origem PRODUTO, CATEGORIA, UNIDADE_MEDIDA.
-- Chave natural: combustivel (= coluna PRODUTO da ANP).
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dim_combustivel (
    id_combustivel  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    combustivel     VARCHAR(60)  NOT NULL,
    categoria       VARCHAR(60),
    unidade_medida  VARCHAR(20),
    CONSTRAINT uq_dim_combustivel UNIQUE (combustivel)
);

-- -----------------------------------------------------------------------------
-- dim_localizacao: origem MUNICIPIO, ESTADO, ESTADO_NOME, REGIAO.
-- Chave natural: (municipio, uf).
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dim_localizacao (
    id_localizacao  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    municipio       VARCHAR(100) NOT NULL,
    uf              CHAR(2)      NOT NULL,
    estado          VARCHAR(50),
    regiao          VARCHAR(5),
    CONSTRAINT uq_dim_localizacao UNIQUE (municipio, uf)
);

-- -----------------------------------------------------------------------------
-- dim_revenda: origem CNPJ, REVENDA, RUA, NUMERO, COMPLEMENTO, BAIRRO, CEP.
-- Chave natural: cnpj. SCD tipo 1 (guarda o cadastro mais recente).
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dim_revenda (
    id_revenda    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cnpj          VARCHAR(18)  NOT NULL,
    nome_revenda  VARCHAR(200),
    rua           VARCHAR(200),
    numero        VARCHAR(30),
    complemento   VARCHAR(200),
    bairro        VARCHAR(100),
    cep           VARCHAR(9),
    CONSTRAINT uq_dim_revenda_cnpj UNIQUE (cnpj)
);

-- -----------------------------------------------------------------------------
-- dim_bandeira: origem BANDEIRA. Fica fora da dim_revenda porque o mesmo
-- posto troca de bandeira ao longo do tempo (103 CNPJs no arquivo analisado).
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dim_bandeira (
    id_bandeira  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bandeira     VARCHAR(100) NOT NULL,
    CONSTRAINT uq_dim_bandeira UNIQUE (bandeira)
);
